### PR TITLE
WIP Update DamageWorker_AddInjury::ApplyDamageToPart patch

### PR DESCRIPTION
**Pull request by JonnyNova**

### CODE REVIEW

**Comment by NoImageAvailable** [comment]
What's this do then?

**Comment by JonnyNova** [comment]
The transpiler would emit invalid IL before, it is valid now. Per the XML still being unfinished it is untested

**Comment by JonnyNova** [comment]
Making it WIP to more clearly communicate that

**Comment by NoImageAvailable** [comment]
This error is fixed in #564

**Pull request closed without merging**
