### PR TITLE
Inital Transpiler logging push

### PR DESCRIPTION
**Pull request by DoomOfMax97**
Added Logging at the start of each Transpiler call.

### CODE REVIEW

**Comment by DoomOfMax97** [comment]
Only got a message for DamageWorker_AddInjury though.

**Comment by NoImageAvailable** [comment]
This tells us nothing about whether the transpiler actually succeeded

**Comment by DoomOfMax97** [comment]
Now it should (at least more than before).

**Comment by DoomOfMax97** [comment]
Also I get this error as well:
Error while instantiating a mod of type CombatExtended.Controller: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: Method Verse.DamageWorker_AddInjury.ApplyDamageToPart(Verse.DamageInfo, Verse.Pawn, Verse.DamageWorker+DamageResult) cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) Verse.DamageWorker_AddInjury:ApplyDamageToPart_Patch1 (object,Verse.DamageInfo,Verse.Pawn,Verse.DamageWorker/DamageResult): IL_004b: call      0x0000000d

**Comment by NoImageAvailable** [comment]
The issue isn't whether the transpiler method *runs* it's whether it can correctly identify the target section of code and make the appropriate adjustments. You'd have to rewrite the transpiler to insert logging into the target method itself, which is probably just as much, if not more work than just testing them by hand.

**Pull request closed without merging**
